name: Release Chart
on:
  push:
    branches:
      - main
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout helm-charts
        uses: actions/checkout@v2
        with:
          repository: ${{ vars.APP_OWNER }}/${{ vars.APP_NAME }}
          ref: refs/heads/main
          path: charts
          token: ${{ secrets.GHCR_TOKEN }}

      - name: Publish the Helm chart
        id: publish-chart
        uses: moikot/chart-publish-action@v1
        with:
          charts_dir: "charts"
          charts_url: "https://${{ vars.APP_OWNER }}.github.io/charts"

      - name: Commit and push helm-charts
        uses: EndBug/add-and-commit@v6
        with:
          author_name: ${{ vars.APP_OWNER }}
          author_email: ${{ vars.APP_OWNER_EMAIL }}
          branch: main
          cwd: charts
          message: "Commit chart ${{ steps.publish-chart.outputs.chart }}"